CREATE DATABASE project2015;
USE project2015;

CREATE TABLE users (
  id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  passwd CHAR(70) NOT NULL,
  a_level BIT NOT NULL DEFAULT 1
);

DROP TABLE users;
TRUNCATE TABLE users;
SELECT * FROM users;